[profile.default]
src = "src"
out = "out"
libs = ["lib"]
ffi = true
solc = "0.8.25"
remappings = [
    'murky/=lib/murky/',
    '@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/',
    'foundry-devops/=lib/foundry-devops',
    'forge-std/=lib/forge-std/src/',
]

# See more config options https://github.com/foundry-rs/foundry/tree/master/config
